name: clock_app
description: A Flutter Analog Clock, Alarm, Stopwatch, and World Clock application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # Formatting (Dates/Time)
  intl: ^0.18.0
  
  # Fonts
  google_fonts: ^5.1.0

  # Audio for Alarms
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
